services:
  database:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - src/core/.env
    volumes:
      - ./database/db-data/:/var/lib/postgresql/data/

  database-test:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    ports:
      - '5433:5432'
    env_file:
      - src/core/.env
    volumes:
      - ./database/db-test-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '15433:80'
    env_file:
      - src/core/.env
    depends_on:
      - database
    volumes:
      - ./database/pgadmin-data/:/var/lib/pgadmin/

  fastapi-stores:
    build:
      context: src
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    expose:
      - 8000
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-level debug --workers 3 --reload