services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./cache/:/data/

  database:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - src/core/.env
    volumes:
      - ./database/db-data/:/var/lib/postgresql/data/

  database-test:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    ports:
      - '5433:5432'
    env_file:
      - src/core/.env
    volumes:
      - ./database/db-test-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '15433:80'
    env_file:
      - src/core/.env
    depends_on:
      - database
    volumes:
      - ./database/pgadmin-data/:/var/lib/pgadmin/

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  fastapi-stores:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: storesapi
    restart: unless-stopped
    environment:
      ENV_STATE: 'dev'
    ports:
      - '8001:8000'
    depends_on:
      - database
      - redis
      - rabbitmq
    expose:
      - 8001
    volumes:
      - ./logs/:/home/logs/
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-level debug --workers 3 --reload